name: CI Symfony

on:
  push:
  pull_request:

jobs:
  symfony-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: pdo, pdo_mysql, intl

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Check for security vulnerabilities
        run: composer audit

      - name: Create database
        run: php bin/console doctrine:database:create --env=test --if-not-exists

      - name: Run migrations
        run: php bin/console doctrine:migrations:migrate --no-interaction --env=test
  
      - name: PHPStan Static Analysis
        run: vendor/bin/phpstan analyse --no-progress --memory-limit=256M
        continue-on-error: true

      - name: Run tests
        run: php bin/phpunit
        env:
          DATABASE_URL: "sqlite:///%kernel.project_dir%/var/test.db"