name: CI Symfony
on:
  push:
  pull_request:

jobs:
  symfony-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
         MYSQL_ROOT_PASSWORD: root
         MYSQL_DATABASE: symfony_test  # sera ignoré, Symfony créera symfony_test_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: pdo, pdo_mysql, intl

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Check for security vulnerabilities
        run: composer audit

      - name: Create database
        run: php bin/console doctrine:database:create --env=test --if-not-exists
        env:
          DATABASE_URL: "mysql://root:root@127.0.0.1:3306/symfony"

      - name: Run migrations
        run: php bin/console doctrine:migrations:migrate --no-interaction --env=test
        env:
          DATABASE_URL: "mysql://root:root@127.0.0.1:3306/symfony"

      - name: PHPStan Static Analysis
        run: vendor/bin/phpstan analyse --no-progress --memory-limit=256M
        continue-on-error: true

#      - name: Run tests
#        run: php bin/phpunit
#        env:
#          DATABASE_URL: "mysql://root:root@127.0.0.1:3306/symfony"